# Generated by Django 4.2.1 on 2023-05-20 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_ID', models.CharField(max_length=8, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('residential_address', models.TextField(default='none', max_length=300)),
                ('in_public_domain', models.BooleanField(default=False)),
                ('created_by_org', models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='memberOfaFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('aadhar', models.CharField(max_length=12, unique=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.familymodel')),
            ],
        ),
    ]
