# Generated by Django 4.2.1 on 2023-05-27 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('transaction_ID', models.CharField(max_length=18)),
                ('purpose', models.TextField()),
                ('given_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.familymodel')),
            ],
        ),
    ]
