# Generated by Django 4.2.1 on 2023-05-27 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
