# Generated by Django 4.2.1 on 2023-05-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_benefit_given_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='given_by',
        ),
    ]
