# Generated by Django 4.2.1 on 2023-05-28 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_benefit_given_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymodel',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
