# Generated by Django 4.2.1 on 2023-07-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_familymodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
