# Generated by Django 4.2.1 on 2023-07-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_benefit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
