# Generated by Django 4.2.1 on 2023-08-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='aboutOrg',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='organization',
            name='localAddress',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='organization',
            name='mobile',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
